name: deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.13
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.ROLE_ARN_GITHUB_ACTIONS_CALL_CLOUDFORMATION }}
          aws-region: ap-northeast-1
      - uses: aws-actions/setup-sam@v2
      - run: pip install poetry
      - run: make build
      - run: make package
        env:
          SAM_ARTIFACT_BUCKET: ${{ secrets.BUCKET_NAME_LAMBDA_ARTIFACT }}
      - run: tar cf layers.tar *
      - uses: actions/upload-artifact@v3
        with:
          name: layers.tar
          path: layers.tar
      - name: deploy
        env:
          IAM_ROLE: ${{ secrets.ROLE_ARN_CLOUD_FORMATION_DEPLOY }}
        run: make deploy
