name: deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_ARTIFACT_BUCKET: ${{ secrets.BUCKET_NAME_LAMBDA_ARTIFACT }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - uses: docker/setup-qemu-action@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.ROLE_ARN_GITHUB_ACTIONS_ADMINISTRATOR }}
          aws-region: ap-northeast-1
      - run: pip install poetry
      - run: make build
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: terraform output
      - run: tar cf layers.tar *
        if: always()
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: layers.tar
          path: layers.tar
